package com.mycompany.conversordivisas;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author diegobecerril
 */
public class Conversor extends javax.swing.JFrame {

    private static final String APIKEY = "https://v6.exchangerate-api.com/v6/1907c772ff6d84acfefcfd96/latest/USD";
    private List<String> historial = new ArrayList<String>();

    /**
     * Creates new form Conversor
     *
     * @throws java.io.IOException
     * @throws java.lang.InterruptedException
     */
    public Conversor() throws IOException, InterruptedException {
        initComponents();
        llenadoComboBox();
    }

    public String getInfoAPI() {
        try {
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder().uri(URI.create(APIKEY)).build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            return response.body();
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    public void llenadoComboBox() throws IOException, InterruptedException {
        try {
            String jsonString = getInfoAPI();

            ObjectMapper mapper = new ObjectMapper();

            //Obtiene los valores de <conversion_rates> 
            //el cual contiene las divisas y sus valores
            JsonNode node = mapper.readTree(jsonString);
            var conversion_rates = node.get("conversion_rates");

            //Agrega elementos a los comboBox
            conversion_rates.fields().forEachRemaining(divisa -> {
                jComboBoxMonedaActual.addItem(divisa.getKey());
                jComboBoxMonedaNueva.addItem(divisa.getKey());
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void llenadoHistorial(String resultado){
        String cadenaFinal = "-----------------------\n" + "    " + resultado + "\n" + "-----------------------\n";
        historial.add(cadenaFinal);
        imprimirHistorial();
    }
    
    public void imprimirHistorial(){
        jTextAreaHistorial.setText("");
        historial.forEach(insercion -> {
            jTextAreaHistorial.append(insercion);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConversor = new javax.swing.JPanel();
        jPanelHistorial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaHistorial = new javax.swing.JTextArea();
        jButtonConvertir = new javax.swing.JButton();
        jButtonIntercambiarMoneda1 = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelMonedaActual = new javax.swing.JLabel();
        jLabelMonedaNueva = new javax.swing.JLabel();
        jLabelFlecha = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jComboBoxMonedaNueva = new javax.swing.JComboBox<>();
        jComboBoxMonedaActual = new javax.swing.JComboBox<>();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelConversion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de monedas");
        setName("Conversor"); // NOI18N
        setResizable(false);

        jPanelConversor.setBackground(new java.awt.Color(84, 145, 207));

        jPanelHistorial.setBackground(new java.awt.Color(203, 188, 141));

        jLabel1.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        jLabel1.setText("Historial");

        jTextAreaHistorial.setEditable(false);
        jTextAreaHistorial.setColumns(20);
        jTextAreaHistorial.setLineWrap(true);
        jTextAreaHistorial.setRows(5);
        jScrollPane1.setViewportView(jTextAreaHistorial);

        javax.swing.GroupLayout jPanelHistorialLayout = new javax.swing.GroupLayout(jPanelHistorial);
        jPanelHistorial.setLayout(jPanelHistorialLayout);
        jPanelHistorialLayout.setHorizontalGroup(
            jPanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistorialLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHistorialLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelHistorialLayout.setVerticalGroup(
            jPanelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHistorialLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonConvertir.setBackground(new java.awt.Color(135, 195, 130));
        jButtonConvertir.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        jButtonConvertir.setText("Convertir!");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jButtonIntercambiarMoneda1.setBackground(new java.awt.Color(135, 195, 130));
        jButtonIntercambiarMoneda1.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        jButtonIntercambiarMoneda1.setText("Intercambiar moneda");
        jButtonIntercambiarMoneda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntercambiarMoneda1ActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        jLabelTitulo.setText("Conversor de monedas");

        jLabelMonedaActual.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        jLabelMonedaActual.setText("Moneda actual");

        jLabelMonedaNueva.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        jLabelMonedaNueva.setText("Moneda nueva");

        jLabelFlecha.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        jLabelFlecha.setText("======>");

        jLabelCantidad.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N
        jLabelCantidad.setText("Cantidad");

        jTextFieldCantidad.setFont(new java.awt.Font("AppleGothic", 1, 13)); // NOI18N

        jLabelConversion.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanelConversorLayout = new javax.swing.GroupLayout(jPanelConversor);
        jPanelConversor.setLayout(jPanelConversorLayout);
        jPanelConversorLayout.setHorizontalGroup(
            jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConversorLayout.createSequentialGroup()
                .addComponent(jPanelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelConversorLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConversorLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabelMonedaActual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMonedaNueva)
                                .addGap(71, 71, 71))
                            .addGroup(jPanelConversorLayout.createSequentialGroup()
                                .addComponent(jButtonIntercambiarMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(278, 278, 278))
                            .addGroup(jPanelConversorLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelConversorLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelConversorLayout.createSequentialGroup()
                                        .addComponent(jComboBoxMonedaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelFlecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxMonedaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConversorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConversorLayout.createSequentialGroup()
                                .addComponent(jLabelTitulo)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConversorLayout.createSequentialGroup()
                                .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelConversorLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabelCantidad))
                                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(169, 169, 169))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConversorLayout.createSequentialGroup()
                                .addComponent(jLabelConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141))))))
        );
        jPanelConversorLayout.setVerticalGroup(
            jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConversorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(33, 33, 33)
                .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonedaActual)
                    .addComponent(jLabelMonedaNueva))
                .addGap(30, 30, 30)
                .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFlecha)
                    .addComponent(jComboBoxMonedaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMonedaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIntercambiarMoneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConversor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelConversor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        try {
            //Obtención de la información de la API
            String jsonString = getInfoAPI();

            ObjectMapper mapper = new ObjectMapper();

            JsonNode node = mapper.readTree(jsonString);
            var conversion_rates = node.get("Convertions_rates");
            
            /*Obtención de la información del usuario
              - Moneda actual
              - Moneda nueva
              - Cantidad 
            */   
            String monedaActual = jComboBoxMonedaActual.getSelectedItem().toString();
            String monedaNueva = jComboBoxMonedaNueva.getSelectedItem().toString();
            double cantidad = Double.parseDouble(jTextFieldCantidad.getText());
            
            //Empate de la información del usuario con la API
            
            //Cálculo de la conversión
            
            double conversion = 0;
            
            String resultado = cantidad + monedaActual + " son " + conversion + monedaNueva;
            
            //Inserción en la parte del historial y su impresión
            llenadoHistorial(resultado);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe insertar un valor numérico", "Error al convertir", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo salió mal :(", "Error al convertir", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    //Intercambio de moneda a convertir
    private void jButtonIntercambiarMoneda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntercambiarMoneda1ActionPerformed
        String auxMonedaActual = jComboBoxMonedaActual.getSelectedItem().toString();
        String auxMonedaNueva = jComboBoxMonedaNueva.getSelectedItem().toString();

        jComboBoxMonedaActual.setSelectedItem(auxMonedaNueva);
        jComboBoxMonedaNueva.setSelectedItem(auxMonedaActual);
    }//GEN-LAST:event_jButtonIntercambiarMoneda1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Conversor().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Conversor.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Conversor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JButton jButtonIntercambiarMoneda1;
    private javax.swing.JComboBox<String> jComboBoxMonedaActual;
    private javax.swing.JComboBox<String> jComboBoxMonedaNueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelConversion;
    private javax.swing.JLabel jLabelFlecha;
    private javax.swing.JLabel jLabelMonedaActual;
    private javax.swing.JLabel jLabelMonedaNueva;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelConversor;
    private javax.swing.JPanel jPanelHistorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaHistorial;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
